### ISSUE TITLE
catchOffline operator should provide an optional callback function

### ISSUE THREAD

**Issue by abdatta** [cyrilletuzi/ngx-pwa-offline#7]
I think instead of redirecting to a route, catchOffline should give us the freedom to do whatever we want incase the request is found to be offline. So can you please provide a callback function in the parameter of catchOffline that will execute when offline. This will give a lot of flexibility on whether we want to redirect to a page or just show a pop up that you are offline.
Thanks.

**Comment by cyrilletuzi** [comment]
Hi @abdatta, thanks for your interest for this lib.

Your suggestion needs some thinking:

- if it's just to detect offline situations and do your own thing, you could just do that in the error callback of your `.subscribe()`: is a lib really necessary for this? or am I missing something?

- not sure having a callback in a RxJS operator follows the guidelines of RxJS: maybe just having an helper function in the lib to detect if the request failed because of offline? which would meet the previous point.

**Comment by cyrilletuzi** [comment]
Closing for housekeeping. Feel free to comment and I'll reopen this issue.
