### ISSUE TITLE
Unable to detect internet connection changes

### ISSUE THREAD

**Issue by panthera** [cyrilletuzi/ngx-pwa-offline#8]
As you have used navigator.onLine in your network.service, there is an issue. The lib will works as expected as long as we turned off/on the network status in browser. It's not working when there is a hard change of the network option. For example manually turn off the the internet connection will not be fired. Am also looking for a solution other than the classic ping solution. Let me know your thoughts on this issue.

**Comment by cyrilletuzi** [comment]
Thanks for your feedback but it's the expected behavior. As mentionned in the README, "be aware the online status is provided by the browser and it is not always reliable: for example, if your computer is connected to a network but with no Internet access, the browser will still says it's online."

I don't think a lib can do better than the browser, except going into hard solutions like pinging, which is not considered in this lib.
